### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by wuyuanyi135** [wuyuanyi135/MicroVision#10]
- [x]  Flattern the parameter service

- [x] Create backing field for all of them

- [ ]  Json.net serialization and deserialization perform on the backing field

- [ ] once deserialziation is done, call all of the OnPropertyChanged. Or, find some easy way, to invoke the setter of each serialized property to restore the values

**Comment by wuyuanyi135** [comment]
1. flatten the obj. still the bound objs are not exposed as root. I may have to use data template to bind the object to ensure knowing its changing.
e.g.
ExposureTime is not bound but ExposureTime.Value is.
When ExposureTime object it self is replaced, it will not be tracked. So I need to use a data template to bind exposure time rather than its memeber.

**Comment by wuyuanyi135** [comment]
It seems like more reasonable to deserialize the private backing fields and invoke the Onpropetyychange for each one. 
However the same problem: if ExposureTime.value is bound, notifying the change of Exposure time does not propagate to the member. Its highly possible that the value will not be updated

**Comment by wuyuanyi135** [comment]
Decision:
1. Service will provide Bindablebase in favor of data binding
2. Should use backing fields for data serialization.
3. Only call the OnPropertyChange of the service class, no any reeper.
4. In the xaml, no binding should be made towards the deep object. It should be done using data template to expand the indexing.

**Comment by wuyuanyi135** [comment]
4 should be tested by a minimal project.
In `service` Bindablebase defines Configuration obj for binding on a data template. The configuration.text is bound in the template.
test 
Whether configuration.text is linked by binding
After deserialize whether the new configuration is still bound

**Comment by wuyuanyi135** [comment]
Also try JSON.net to deserialize to this and see if empty objs are discarded.
